spring:
  profiles:
    active: local
  mvc:
    throw-exception-if-no-handler-found: true
  h2:
    console:
      enabled: true
  datasource:
    initialization-mode: ALWAYS
    sql-script-encoding: UTF-8
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:url-shortening-service
    username: sa
    password:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
        use_sql_comments: true
  output:
    ansi:
      enabled: ALWAYS

logging:
  level:
    root: INFO
    org.springframework.web: ERROR
    org.hibernate: DEBUG